apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: green-ns
namePrefix: green
commonLabels:
  team: green
bases:
  - ../../platform/team
patchesStrategicMerge:
  - patches.yaml