apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: -apps
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
  timeout: 2m
  serviceAccountName: thisMustBeReplaced
