apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../platform/core
  - ../../teams/team-blue
  - ../../teams/team-green
patches:
  - path: blue-patches.yaml
    target:
      kind: Kustomization
      labelSelector: team=blue
  - path: green-patches.yaml
    target:
      kind: Kustomization
      labelSelector: team=green